services:
  # Frontend React application
  frontend:
    build: .
    container_name: jacket-customizer-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    stdin_open: true
    tty: true

  # Optional Flask backend service
  backend:
    image: python:3.12-slim
    container_name: jacket-customizer-backend
    working_dir: /app
    command: >
      bash -c "pip install -r requirements.txt &&
              python app.py"
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development