version: '3.8'

services:
  # Frontend React application
  frontend:
    build:
      context: .
      dockerfile: ./docker_setup/react_client.Dockerfile
    container_name: jacket-customizer-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5001/api
    depends_on:
      - backend
    stdin_open: true
    tty: true

  # Flask backend service
  backend:
    build:
      context: .
      dockerfile: ./docker_setup/flask_server.Dockerfile
    container_name: jacket-customizer-backend
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app
      - ./research_data:/app/research_data
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=True
      - FLASK_PORT=5001

# Docker network for communication between services
networks:
  default:
    name: jacket-customizer-network